name: Channel digest testing

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Which manual command to run'
        required: false
        default: 'digest'
        type: choice
        options:
          - digest
          - latest
          - today
          - recent
      count:
        description: 'Max items to include (digest) or N for recent'
        required: false
        default: '50'
      force_window_hours:
        description: 'Override WINDOW_HOURS for testing (e.g., 720 for 30 days)'
        required: false
        default: '720'
        type: string

permissions:
  contents: read

# Prevent overlapping runs that could cause cache conflicts
concurrency:
  group: channel-digest-testing-${{ github.ref }}
  cancel-in-progress: false

env:
  TARGET_REPOS: '["SimplifyJobs/Summer2026-Internships","vanshb03/Summer2026-Internships"]'
  LISTINGS_PATH: '.github/scripts/listings.json'
  DATE_FIELD: 'date_posted'
  DATE_FALLBACK: 'date_updated'
  WINDOW_HOURS: '1' # 1 hour for regular digest
  SEEN_TTL_DAYS: '14' # Channel digest: longer TTL for less frequent updates
  STATE_DIR: '.state/channel-digest-testing' # Separate state directory for testing

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests

      # Use separate cache for channel digest testing TTL state
      - name: Restore channel digest testing state
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: .state/channel-digest-testing
          key: channel-digest-testing-state-v1-${{ github.run_id }}
          restore-keys: |
            channel-digest-testing-state-v1-

      - name: Run digest to testing channel
        if: github.event.inputs.command == 'digest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_TESTING }}
          TARGET_REPOS: ${{ env.TARGET_REPOS }}
          LISTINGS_PATH: ${{ env.LISTINGS_PATH }}
          DATE_FIELD: ${{ env.DATE_FIELD }}
          DATE_FALLBACK: ${{ env.DATE_FALLBACK }}
          WINDOW_HOURS: ${{ github.event.inputs.force_window_hours || env.WINDOW_HOURS }}
          SEEN_TTL_DAYS: ${{ env.SEEN_TTL_DAYS }}
          COUNT: ${{ github.event.inputs.count }}
          STATE_DIR: ${{ env.STATE_DIR }}
        run: python .github/scripts/send_digest_multi.py

      - name: Send latest listing to testing channel
        if: github.event.inputs.command == 'latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_TESTING }}
          TARGET_REPO: 'vanshb03/Summer2026-Internships'
          LISTINGS_PATH: ${{ env.LISTINGS_PATH }}
          MESSAGE_PREFIX: '🧪 Testing'
        run: python .github/scripts/send_latest_listing.py

      - name: Send today's listings to testing channel
        if: github.event.inputs.command == 'today'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_TESTING }}
          TARGET_REPO: 'vanshb03/Summer2026-Internships'
          LISTINGS_PATH: ${{ env.LISTINGS_PATH }}
          MESSAGE_PREFIX: '🧪 Testing'
        run: python .github/scripts/send_todays_listings.py

      - name: Send recent listings to testing channel
        if: github.event.inputs.command == 'recent'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_TESTING }}
          TARGET_REPO: 'vanshb03/Summer2026-Internships'
          LISTINGS_PATH: ${{ env.LISTINGS_PATH }}
          COUNT: ${{ github.event.inputs.count }}
          MESSAGE_PREFIX: '🧪 Testing'
        run: python .github/scripts/send_recent_listings.py

      # Save channel digest testing TTL state (separate from production)
      - name: Save channel digest testing state
        if: always()
        uses: actions/cache/save@v4
        with:
          path: .state/channel-digest-testing
          key: channel-digest-testing-state-v1-${{ github.run_id }}
