name: Channel digest (8h)

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:
    inputs:
      command:
        description: 'Which manual command to run'
        required: false
        default: 'digest'
        type: choice
        options:
          - digest
          - latest
          - today
          - recent
      count:
        description: 'Max items to include (digest) or N for recent'
        required: false
        default: '50'

permissions:
  contents: read

env:
  TARGET_REPOS: '["SimplifyJobs/Summer2026-Internships","vanshb03/Summer2026-Internships"]'
  LISTINGS_PATH: '.github/scripts/listings.json'
  DATE_FIELD: 'date_posted'
  DATE_FALLBACK: 'date_updated'
  WINDOW_HOURS: '8'

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install requests

      - name: Run 8h digest to channel
        if: github.event_name == 'schedule' || github.event.inputs.command == 'digest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_CHANNEL }}
          TARGET_REPOS: ${{ env.TARGET_REPOS }}
          LISTINGS_PATH: ${{ env.LISTINGS_PATH }}
          DATE_FIELD: ${{ env.DATE_FIELD }}
          DATE_FALLBACK: ${{ env.DATE_FALLBACK }}
          WINDOW_HOURS: ${{ env.WINDOW_HOURS }}
          COUNT: ${{ github.event.inputs.count }}
        run: python .github/scripts/send_digest_multi.py

      - name: Send latest listing to channel (manual runs only)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.command == 'latest'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_CHANNEL }}
          TARGET_REPO: "vanshb03/Summer2026-Internships"
          LISTINGS_PATH: ${{ env.LISTINGS_PATH }}
        run: python .github/scripts/send_latest_listing.py

      - name: Send today's listings to channel (manual runs only)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.command == 'today'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_CHANNEL }}
          TARGET_REPO: "vanshb03/Summer2026-Internships"
          LISTINGS_PATH: ${{ env.LISTINGS_PATH }}
        run: python .github/scripts/send_todays_listings.py

      - name: Send recent listings to channel (manual runs only)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.command == 'recent'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID_CHANNEL }}
          TARGET_REPO: "vanshb03/Summer2026-Internships"
          LISTINGS_PATH: ${{ env.LISTINGS_PATH }}
          COUNT: ${{ github.event.inputs.count }}
        run: python .github/scripts/send_recent_listings.py
